### ISSUE TITLE
Using in Objective-C project

### ISSUE THREAD

**Issue by nikolaenkoag** [dbart01/Gryphin#6]
Hi! Can i use in Objective-C project? How to installation?

**Comment by dbart01** [comment]
Unfortunately, `Gryphin` has types that can't be represented in Objective-C making it only available to Swift. The workaround is to write your network layer in Swift using Objective-C friendly types and classes (avoid generics, non-integer type enums, etc). Doing will allow your Objective-C code to interface with the Swift network layer.
