### ISSUE TITLE
Build as a framework

### ISSUE THREAD

**Issue by nikolaenkoag** [dbart01/Gryphin#7]
Hi! Whether it is possible to build as a framework? For swift project?

**Comment by dbart01** [comment]
I'm not sure I understand your question. The output of the build process is a generated `Gryphin.framework` that you have to import into your swift project:
```swift
import Gryphin
```

**Comment by nikolaenkoag** [comment]
Sorry for my english. I insert it's project as a sub-project of my application, i.e i insert `Gryphin.xcodeproj` file in my product. And it is possible to build so that to insert only `Gryphin.framework`?

**Comment by dbart01** [comment]
There's no built in support for this (yet), but you can do so manually. You'll need to build `Gryphin.framework` for all architectures and then drop it into your project. You'll lose build-time schema updates, however.

**Comment by nikolaenkoag** [comment]
Thank you. I removed the mac os targets and the project built with other objective-c frameworks.
