### ISSUE TITLE
Are mutations supported?

### ISSUE THREAD

**Issue by flexzuu** [dbart01/Gryphin#8]
Hey a quick question. The docs don't explicitly state if mutations are supported or not?
I would be willing to change that and make a PR for the README.md if you could answer me the question.

**Comment by dbart01** [comment]
Yes, mutations are supported. If your schema defines mutations, there's nothing extra that you have to do.

**Comment by flexzuu** [comment]
Perfect thanks i will try to put a example in the readme after i have used the lib. We can close the issue.
